{% set name = "iommi" %}
{% set version = "7.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/iommi-{{ version }}.tar.gz
  sha256: 8b20ed46e7c223dd5e34910e56def9410d2d71f61ac23bb78bf7adaac6e34518

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=3.2
    - pyparsing

test:
  imports:
    - iommi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/iommirocks/iommi
  doc_url: https://docs.iommi.rocks/en/latest/
  summary: iommi is a high level framework built on django
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
