{% set name = "iommi" %}
{% set version = "7.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/iommi-{{ version }}.tar.gz
  sha256: 1d062ea0b91b7bd94bfea87587b99d00c600df589ba0321d08e9a4c71495e169

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=3.2
    - pyparsing

test:
  imports:
    - iommi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/iommirocks/iommi
  doc_url: https://docs.iommi.rocks/en/latest/
  summary: iommi is a high level framework built on django
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
