schema_version: 1

context:
  name: iommi
  version: "7.21.2"
  # Not speficied upstream but uses code that is only supported in 3.12+
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/iommi-${{ version }}.tar.gz
  sha256: 657418e1d5a03a02647ce7255c53aff194922940b83449427924acdd42775303

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - django >=3.2
    - pyparsing

tests:
  - python:
      imports:
        - iommi
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: iommi is a high level framework built on django
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/iommirocks/iommi
  documentation: https://docs.iommi.rocks/en/latest/

extra:
  recipe-maintainers:
    - thewchan
