schema_version: 1

context:
  name: iommi
  version: "7.15.1"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/iommi-${{ version }}.tar.gz
  sha256: d5cc59b5d6df5265e4be2ed8cdbc60b01289e3bf1bbf0cc1a3a046b1ecebb600

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - django >=3.2
    - pyparsing

tests:
  - python:
      imports:
        - iommi
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: iommi is a high level framework built on django
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/iommirocks/iommi
  documentation: https://docs.iommi.rocks/en/latest/

extra:
  recipe-maintainers:
    - thewchan
